version: '3.7'
services:
  app-angular:
    container_name: app-angular
    build:
      context: ./angular-app
  app-react:
    container_name: app-react
    build:
      context: ./react-app
  app-vue:
    container_name: app-vue
    build:
      context: ./vue-app
  orchestrator:
    container_name: orchestrator
    ports:
      - "80:80"
    depends_on:
      - app-angular
      - app-react
      - app-vue
    build:
      context: .
